AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Include:
    - '**/*.rb'
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'script/**/*'

Layout/LineLength:
  Max: 125

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
